### ISSUE TITLE
Error Server/main.lua 50

### ISSUE THREAD

**Issue by LoffeKoffe** [Zinix11/Esx_Advanced_Holdup#1]
> 

 loading script server/main.lua in resource esx_advanced_holdup: server/main.lua:50: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:50: in function 'AddMoneyToBanks'
        server/main.lua:164: in main chunk
Failed to load script server/main.lua.

>

**Comment by Zinix11** [comment]
Oh thanks, I think I uploaded the wrong config I'll fix

**Comment by Zinix11** [comment]
Ok, the config should be the right one now.
