### ISSUE TITLE
error after your latest changes

### ISSUE THREAD

**Issue by LoffeKoffe** [Zinix11/Esx_Advanced_Holdup#2]
`Error loading script server/main.lua in resource esx_advanced_holdup: server/main.lua:50: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:50: in function 'AddMoneyToBanks'
        server/main.lua:164: in main chunk
Failed to load script server/main.lua.`

**Comment by Zinix11** [comment]
Hmm that is weird I will look into it but I'm pretty sure I didn't change anything to do with addmoneytobanks

**Comment by LoffeKoffe** [comment]
Nope it was my fault and i forgot to remove this, sorry!
